### ISSUE TITLE
Issue with require-statement mutation in Gambit tool: Expression replacement not implemented

### ISSUE THREAD

**Issue by Sta1400** [Certora/gambit#20]
As a user of the Gambit tool, I have noticed an issue with the require-statement mutation, where the mutation is not fully implemented according to the documentation.

According to the Gambit documentation, the require-statement mutation is intended to negate or change the expression inside a require statement. The documentation suggests replacing the expression with "true" or "!<exp>".

However, I have observed that the mutation only replaces the expression with "!<exp>". The replacement with "true" is not implemented.

I believe that this is a significant limitation of the mutation. The replacement with "true" would be useful in cases where the require statement is used to check a condition that should always be true. This would allow this mutation to generate more varied and meaningful mutants.

I would like to suggest that the Gambit team review the implementation of the require-statement mutation and consider adding the ability to replace the expression with "true" or other values, as suggested in the documentation.

Thank you for your attention to this matter.

**Comment by BenTheKush** [comment]
I will double check tomorrow, but I think this might be fixed in #14, so if you go to the `ben/mutator-refactor` branch it _may_ be done? As I said in another issue, I'm going to be doing a fair amount of work on mutation operators in another PR coming soon, but if this is broken I'll get it up and running for you.

**Comment by BenTheKush** [comment]
@Sta1400 I've merged #14 into `master`, this should be correctly implemented now.

I've changed the semantics of require mutation: instead of mutating to `true` and `!c` I'm mutating to `true` and `false`. The reason is that both of these mutations are harder to detect than `!c`, and any time `!c` is detected, one of either `true` or `false` would be detected. This makes `!c` an inefficient mutant with lower utility than one of the other two mutants.

I'm closing this issue, but let me know if you are still encountering issues and we can reopen it. Thanks for your patience!
